# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rdk_synaptics"
BBFILE_PATTERN_rdk_synaptics = "^${LAYERDIR}/"
BBFILE_PRIORITY_rdk_synaptics = "7"

LAYERDEPENDS_rdk_synaptics = "core"
LAYERSERIES_COMPAT_rdk_synaptics = "kirkstone"
